apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unzip
spec:
  description: >-
    unzip file from workspace
  params:
    - name: sub-dirs
      type: array
      description: the sub-directories under workspace
      default: ['.']
  workspaces:
    - name: storage
      persistentVolumeClaim:
        claimName: transfer-pipeline
  results:
    - name: README
      description: echo the README of the repo
  steps:
    - name: unzip-file
      image: busybox
      command:
        - unzip
      args:
        - '$(params.sub-dirs)'
      workingDir: '$(workspaces.directory.path)'
#    - name: show-readme
#      image: busybox
#      script: |
#        #!/bin/sh
#        [[ -f $(workspaces.directory.path)/README.md ]] && cat $(workspaces.directory.path)/README.md | tee /tekton/results/README && exit 0
#        [[ -f $(workspaces.directory.path)/README.adoc ]] && cat $(workspaces.directory.path)/README.adoc | tee /tekton/results/README && exit 0
